Add emote grouping to /twitch/subscriber_emotes
Decicus/DecAPI pull request #61
Opened 2020-05-20 12:30 UTC by Kriper1111

Additions:
 - /twitch/subscriber_emotes now has new url parameter, `tiers`. If combined with `json` returns channel emotes, grouped by subscription tier. Response format:
```
{
  "emotes": {
    "tier1": [*channel emotes for $4.99 sub*],
    "tier2": [*channel emote for $9.99 sub*],
    "tier3": [*channel emote for $24.99 sub*]
  }
}
```
Available only when json header or json parameter specified.

I tried to make it look good and make sense, but I didn't really succeed at that. But it works.

2020-05-20 13:01 UTC, Decicus requested changes
I haven't tested this myself yet, but I reviewed the code and noticed a few things I'd like to have "fixed" (it's mostly nitpicking). I'll test it later today if I have time.

Thanks for the pull request :)

2020-05-20 13:01 UTC, Decicus commented on app/Http/Controllers/TwitchController.php
> +        $wantsPlans = ($request -> exists('tiers') && $wantsJson);
Consistency: No spaces before and after object arrow operators (`->`)

2020-05-20 13:01 UTC, Decicus commented on app/Http/Resources/TwitchEmotes/Plans.php
> +// aaaaaaaaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Please either remove this comment or write something sensible.

2020-05-20 13:01 UTC, Decicus commented on app/Http/Resources/TwitchEmotes/Plans.php
> +    // AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Same as the previous review comment: Either remove it or write something that actually describes the function.

2020-05-20 13:01 UTC, Decicus commented on app/Http/Resources/TwitchEmotes/Plans.php
> +                    ->map(function($plans, $AAAAAa) use($emotes){
If you're not gonna use the `key` parameter (`$AAAAAa`), you don't have to include it in the function and can just remove it.

2020-05-20 13:01 UTC, Decicus commented on app/Http/Resources/TwitchEmotes/Plans.php
> +                        $accumulator = array();
Consistency: Please use the `[]` syntax instead of `array()`

2020-05-20 13:01 UTC, Decicus commented on app/Http/Resources/TwitchEmotes/Plans.php
> +                        foreach($emotes as $emote){
Consistency: Space after `foreach` and before the parenthesis.

2020-05-20 13:01 UTC, Decicus commented on app/Http/Resources/TwitchEmotes/Plans.php
> +                            if($emote['emoticon_set'] == $plans){
Consistency: Space after `if` and before the parenthesis.
Also: Please use strict/identical checking (`===`) wherever possible.

2020-05-20 13:01 UTC, Decicus commented on app/Http/Resources/TwitchEmotes/Plans.php
> +    // how do i do that documentation thing?
Multi-line comments like this is perfectly fine in my opinion, but I personally use "[DocBlocks](https://docs.phpdoc.org/latest/guides/docblocks.html)" (though I'm pretty 'lax' about those rules) with the help of this extension for VS Code: https://marketplace.visualstudio.com/items?itemName=neilbrayfield.php-docblocker

You don't have to use it yourself obviously, but since you were asking :)

2020-05-20 13:41 UTC, Kriper1111 commented on app/Http/Resources/TwitchEmotes/Plans.php
> +                            if($emote['emoticon_set'] == $plans){
> Also: Please use strict/identical checking (`===`) wherever possible.

The thing is: in API response, emoticon set ID in "plans" is a string and in "emotes" it's an integer. I can try to convert them in Emote class in your API. Hopefully it won't break anything

2020-05-20 13:46 UTC, Decicus commented on app/Http/Resources/TwitchEmotes/Plans.php
> +                            if($emote['emoticon_set'] == $plans){
You can type cast the int value to a string and compare: `if ((string) $emote['emoticon_set'] === $plans)`

2020-05-26 20:22 UTC, Decicus approved these changes

2020-05-26 20:22 UTC, merged